[package]
name = "mandatum-native-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
fault-injection = []

[dependencies]
glyphon.workspace = true
lru.workspace = true
mandatum-scene.workspace = true
serde.workspace = true
sys-locale.workspace = true
ttf-parser.workspace = true
unicode-script.workspace = true
wgpu.workspace = true
winit.workspace = true
